

* Descripcion del sistema: 
El principal objetivo de este proyecto es crear y desarrollar un sistema informático para controlar y mejorar la eficiencia de la gestión y administracion de un hospital, por ejemplo, todo lo relacionado con los pacientes, empresas farmaceuticas, médicos, enfermeros, etc. Además se permitirá la consulta y la reserva de citas con un especialista asignado.
El software debe gestionar la privacidad de los pacientes, su historial médico y también permitirnos analizar datos sobre los pacientes para una mejor organización o solución a un problema.

La idea principal consiste en un sistema informático principal alojado en el propio hospital, con distintos niveles de acceso y restricciones dependiendo de la identificación del usuario. Así:
+ si se es un paciente sólo se tendrá acceso a la información más básica, como puede ser pedir citas e información sobre los servicios que ofrece el hospital o su localización
- si se es un trabajador del hospital se tendrá acceso a otros detalles, como la gestión de las camas y equipo del hospital
+ si se tiene un cargo importante dentro del manejo del hospital se podría considerar el proporcionar acceso restringido a otras zonas de control del software
- finalmente, el equipo informático de mantenimiento del software tendrá un acceso a todos y cada uno de los detalles de este

Debe poder controlar las instalaciones del centro para asegurar la calidad y el funcionamiento de las máquinas.

El sistema informático debe ser eficiente en la resolución y asignacion de pacientes a salas  dependiendo de varios parámetros, como pueden ser la gravedad del problema o la edad.

* Objetivos principales:
 - Facilitar el uso del software a un nivel básico, ya que cualquier persona que no tenga manejo con la tecnologia pueda utilizar el software con facilidad teniendo en cuenta que puede ser utilizado por personas mayores.
 + Respuesta de calidad y eficiente en el tiempo a los pacientes y clientes, evitando errores y atendiendo en un orden segun prioridad.
 - Gestión de los trabajadores, sus horarios de trabajo, salas. gestión de la economia interna del centro, mensajeria entre trabajadores y gestion de cargos.
 + Control de toda la información de los clientes para cada médico, para consulta rapida y eficiente.
 
